import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
interface IChildren {
  children: React.ReactNode,
  auth: React.ReactNode,
  modal: React.ReactNode
}

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: IChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{ props.children }</div>
        <div>{ props.auth }</div>
        <div>{ props.modal }</div>
      </body>
    </html>
  )
}
